# Generated by Django 3.1.6 on 2024-12-19 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pokescrap', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='to_scrap',
            old_name='link',
            new_name='url',
        ),
    ]
