# Generated by Django 3.1.6 on 2024-12-19 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pokescrap', '0002_auto_20241219_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='to_scrap',
            name='name',
            field=models.CharField(default='Unknown', max_length=150),
        ),
    ]
