# Generated by Django 3.1.6 on 2024-12-27 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pokescrap', '0003_to_scrap_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='to_scrap',
            name='is_scraped',
            field=models.BooleanField(default=False),
        ),
    ]
