# Generated by Django 5.1.4 on 2024-12-27 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pokescrap', '0004_to_scrap_is_scraped'),
    ]

    operations = [
        migrations.AlterField(
            model_name='to_scrap',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
