# Generated by Django 3.1.6 on 2024-12-19 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='To_Scrap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_element', models.CharField(choices=[('T', 'Talent'), ('A', 'Attaque'), ('P', 'Pokemon')], max_length=1)),
                ('link', models.CharField(max_length=150)),
            ],
        ),
    ]
