# Generated by Django 3.1.6 on 2024-12-19 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pokedata', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='To_Scrap',
        ),
    ]
