# Generated by Django 3.1.6 on 2024-12-19 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pokedata', '0003_attaque_pokemon_talent'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='picture_url',
            field=models.CharField(default='', max_length=150),
        ),
    ]
