# Generated by Django 5.1.4 on 2024-12-27 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pokedata', '0004_pokemon_picture_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attaque',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='talent',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
