# Generated by Django 5.1.4 on 2024-12-27 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pokedata', '0005_alter_attaque_id_alter_pokemon_id_alter_talent_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='talent',
            name='description',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='talent',
            name='effet_combat',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='talent',
            name='effet_terrain',
            field=models.CharField(default='', max_length=150),
        ),
    ]
